// Actions for transactions reducer
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const FILTER_TRANSACTIONS = "FILTER_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
// Actions for Auth reducer
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
// LOGIN & LOGOUT
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// EMAIL VERIFY
export const VERIFY_LOADING = "VERIFY_LOADING";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";
// EMAIL CONFIRM
export const CONFRIM_LOADING = "CONFRIM_LOADING";
export const CONFIRM_SUCCESS = "CONFIRM_SUCCESS";
export const CONFIRM_FAIL = "CONFIRM_FAIL";
// UPDATE USER DETAILS
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
// CONFIRM DELTE
export const CONFIRM_DELETE = "CONFIRM_DELETE";
export const RESET_DELETE = "RESET_DELETE";
// ERROR
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
